import { dataSourceDefinitions } from '../dataSources'
import type { DataSourceId, EditorState, InterfaceScale, OverlayItem } from '../types'
import { resolutions } from '../data'
import { Toggle } from './Toggle'
type Props = { state: EditorState; item: OverlayItem; update: (patch: Partial<EditorState>) => void; updateItem: (patch: Partial<OverlayItem>) => void; onTestAlert: () => void }
const Help = ({ children }: { children: string }) => <span className="help" data-tip={children}>i</span>
const Slider = ({ label, value, onChange, suffix = '%', min = 0, max = 100 }: { label: string; value: number; suffix?: string; min?: number; max?: number; onChange: (value: number) => void }) => <label className="setting slider"><span>{label}</span><output>{value}{suffix}</output><input type="range" min={min} max={max} value={value} onChange={e => onChange(Number(e.target.value))} /></label>
export function Settings({ state, item, update, updateItem, onTestAlert }: Props) {
  const setResolution = (value: string) => { if (value === 'custom') update({ customResolution: true }); else update({ customResolution: false, resolution: resolutions.find(r => r.label === value)! }) }
  const setCustom = (key: 'width' | 'height', value: number) => update({ resolution: { ...state.resolution, [key]: Math.max(320, value), label: 'Пользовательское' } })
  const usesDataSource = ['chat', 'donation', 'subscriber', 'follower', 'alert'].includes(item.id)
  const availableSources = dataSourceDefinitions.filter(source => source.id === 'demo' || state.dataSources[source.id].status === 'connected')
  return <aside className="settings glass"><div className="panel-heading"><p>Свойства</p><h2>{item.title}</h2></div><section className="settings-section"><h3>Разрешение трансляции</h3><select value={state.customResolution ? 'custom' : state.resolution.label} onChange={e => setResolution(e.target.value)}>{resolutions.map(r => <option key={r.label}>{r.label}</option>)}<option value="custom">Пользовательское</option></select>
    {state.customResolution && <div className="custom-resolution"><label>Ширина<input type="number" value={state.resolution.width} onChange={e => setCustom('width', Number(e.target.value))} /></label><label>Высота<input type="number" value={state.resolution.height} onChange={e => setCustom('height', Number(e.target.value))} /></label></div>}
  </section><section className="settings-section"><div className="setting-line"><span>Безопасная область <Help>Показывает область экрана, которую рекомендуется оставить свободной, чтобы оверлей не закрывал важные элементы игры.</Help></span><Toggle checked={state.showSafeZone} onChange={showSafeZone => update({ showSafeZone })} label="Безопасная область" /></div><div className="setting-line"><span>Фон предпросмотра</span><select value={state.background} onChange={e => update({ background: e.target.value as EditorState['background'] })}><option value="game">Игровой фон</option><option value="dark">Тёмный фон</option><option value="light">Светлый фон</option><option value="transparent">Прозрачность</option></select></div></section>
  <section className="settings-section"><h3>Отображение</h3><div className="setting-line"><span>Показывать элемент</span><Toggle checked={item.enabled} onChange={enabled => updateItem({ enabled })} label={item.title} /></div><Slider label="Ширина блока" value={Math.round(item.size.width / 0.4)} onChange={v => updateItem({ size: { ...item.size, width: Math.max(8, v * .4) } })} /><Slider label="Высота блока" value={Math.round(item.size.height / 0.4)} onChange={v => updateItem({ size: { ...item.size, height: Math.max(4, v * .4) } })} /><Slider label="Размер текста" value={item.textSize} min={50} max={200} onChange={textSize => updateItem({ textSize })} /></section>
  {usesDataSource && <section className="settings-section"><h3>Источник данных</h3><label className="setting">Откуда получать события<select value={availableSources.some(source => source.id === item.dataSourceId) ? item.dataSourceId : 'demo'} onChange={event => updateItem({ dataSourceId: event.target.value as DataSourceId })}>{availableSources.map(source => <option value={source.id} key={source.id}>{source.title}</option>)}</select></label><p className="setting-hint">Доступны демонстрационные данные и подключённые платформы.</p></section>}
  {item.id === 'camera' && <section className="settings-section"><h3>Камера</h3><div className="position-grid">{[['Слева сверху', 3, 4], ['Справа сверху', 77, 4], ['Слева снизу', 3, 68], ['Справа снизу', 77, 68]].map(([label, x, y]) => <button key={String(label)} type="button" onClick={() => updateItem({ position: { x: Number(x), y: Number(y) } })}>{label}</button>)}</div><Slider label="Закругление рамки" value={state.cameraRadius} suffix=" px" onChange={cameraRadius => update({ cameraRadius })} /><Slider label="Толщина рамки" value={state.cameraBorder} suffix=" px" onChange={cameraBorder => update({ cameraBorder })} /><Slider label="Интенсивность свечения" value={state.cameraGlow} onChange={cameraGlow => update({ cameraGlow })} /></section>}
  {item.id === 'chat' && <section className="settings-section"><h3>Чат зрителей</h3><Slider label="Прозрачность фона" value={item.opacity} onChange={opacity => updateItem({ opacity })} /><label className="setting">Количество сообщений<select value={state.chatMessages} onChange={e => update({ chatMessages: Number(e.target.value) as 3 | 5 | 7 | 10 })}>{[3, 5, 7, 10].map(v => <option key={v}>{v}</option>)}</select></label><div className="setting-line"><span>Показывать время</span><Toggle checked={state.chatTime} onChange={chatTime => update({ chatTime })} label="Время сообщений" /></div></section>}
  {item.id === 'clock' && <section className="settings-section"><h3>Часы</h3><div className="setting-line"><span>Показывать время</span><Toggle checked={state.clockTime} onChange={clockTime => update({ clockTime })} label="Время" /></div><div className="setting-line"><span>Показывать дату</span><Toggle checked={state.clockDate} onChange={clockDate => update({ clockDate })} label="Дата" /></div></section>}
  {item.id === 'alert' && <section className="settings-section"><button type="button" className="primary-button" onClick={onTestAlert}>Показать тестовое уведомление</button></section>}
  <section className="settings-section"><h3>Общее оформление</h3><label className="color-setting">Основной цвет подсветки<input type="color" value={state.primaryColor} onChange={e => update({ primaryColor: e.target.value })} /><code>{state.primaryColor}</code></label><label className="color-setting">Дополнительный цвет подсветки<input type="color" value={state.secondaryColor} onChange={e => update({ secondaryColor: e.target.value })} /><code>{state.secondaryColor}</code></label><label className="setting">Размер интерфейса оверлея<select value={state.interfaceScale} onChange={e => update({ interfaceScale: e.target.value as InterfaceScale })}><option value="compact">Компактный</option><option value="normal">Обычный</option><option value="large">Крупный</option></select></label></section>
 </aside>
}
